package Bussiness.Entities;

/**
 * Entidad que representa las estadísticas de una partida en un momento dado.
 */
public class Stat {
	private int idStat;
	private int idGames;
	private int minuteMark;
	private double moneyAtMinute;
	private int manualClicksTotal;
	private double autoGeneratedTotal;
	private float maxProductionRate;
	private double upgradesExpenses;

	/**
	 * Constructor completo para recuperar datos de la base de datos.
	 */
	public Stat(int idStat, int idGames, int minuteMark, double moneyAtMinute,
				int manualClicksTotal, double autoGeneratedTotal,
				float maxProductionRate, double upgradesExpenses) {
		this.idStat = idStat;
		this.idGames = idGames;
		this.minuteMark = minuteMark;
		this.moneyAtMinute = moneyAtMinute;
		this.manualClicksTotal = manualClicksTotal;
		this.autoGeneratedTotal = autoGeneratedTotal;
		this.maxProductionRate = maxProductionRate;
		this.upgradesExpenses = upgradesExpenses;
	}

	/**
	 * Constructor simplificado para crear nuevos registros desde la lógica.
	 */
	public Stat(int idGames, int minuteMark, double moneyAtMinute) {
		this.idGames = idGames;
		this.minuteMark = minuteMark;
		this.moneyAtMinute = moneyAtMinute;
	}

	public int getIdStat() { return idStat; }
	public void setIdStat(int idStat) { this.idStat = idStat; }

	public int getIdGames() { return idGames; }
	public void setIdGames(int idGames) { this.idGames = idGames; }

	public int getMinuteMark() { return minuteMark; }
	public void setMinuteMark(int minuteMark) { this.minuteMark = minuteMark; }

	public double getMoneyAtMinute() { return moneyAtMinute; }
	public void setMoneyAtMinute(double moneyAtMinute) { this.moneyAtMinute = moneyAtMinute; }

	public int getManualClicksTotal() { return manualClicksTotal; }
	public void setManualClicksTotal(int manualClicksTotal) { this.manualClicksTotal = manualClicksTotal; }

	public double getAutoGeneratedTotal() { return autoGeneratedTotal; }
	public void setAutoGeneratedTotal(double autoGeneratedTotal) { this.autoGeneratedTotal = autoGeneratedTotal; }

	public float getMaxProductionRate() { return maxProductionRate; }
	public void setMaxProductionRate(float maxProductionRate) { this.maxProductionRate = maxProductionRate; }

	public double getUpgradesExpenses() { return upgradesExpenses; }
	public void setUpgradesExpenses(double upgradesExpenses) { this.upgradesExpenses = upgradesExpenses; }
}