package Bussiness.Entities;

/**
 * Entidad que captura una instantánea del progreso del jugador en un momento dado.
 * Se utiliza principalmente para persistir el historial minuto a minuto y
 * permitir la visualización de métricas de rendimiento.
 */
public class Stat {
	private int idStat;
	private int idGames;
	private int minuteMark;
	private double moneyAtMinute;
	private int manualClicksTotal;
	private double autoGeneratedTotal;
	private float maxProductionRate;
	private double upgradesExpenses;

	/**
	 * Constructor completo para el registro de métricas.
	 *
	 * @param idStat ID del registro.
	 * @param idGames Partida asociada.
	 * @param minuteMark Marca temporal (minuto de la partida).
	 * @param moneyAtMinute Dinero poseído en ese instante.
	 * @param manualClicksTotal Acumulado de clicks manuales.
	 * @param autoGeneratedTotal Acumulado de café generado automáticamente.
	 * @param maxProductionRate Récord de tasa de producción alcanzado.
	 * @param upgradesExpenses Inversión total realizada hasta el momento.
	 */
	public Stat(int idStat, int idGames, int minuteMark, double moneyAtMinute,
				int manualClicksTotal, double autoGeneratedTotal,
				float maxProductionRate, double upgradesExpenses) {
		this.idStat = idStat;
		this.idGames = idGames;
		this.minuteMark = minuteMark;
		this.moneyAtMinute = moneyAtMinute;
		this.manualClicksTotal = manualClicksTotal;
		this.autoGeneratedTotal = autoGeneratedTotal;
		this.maxProductionRate = maxProductionRate;
		this.upgradesExpenses = upgradesExpenses;
	}

	/**
	 * Obtiene el minuto exacto de la partida en el que se capturó la métrica.
	 * @return El marcador de tiempo en minutos.
	 */
	public int getMinuteMark() {
		return minuteMark;
	}

	/**
	 * Obtiene la cantidad total de dinero o café que poseía el jugador en ese minuto específico.
	 * @return El saldo acumulado en el momento de la muestra.
	 */
	public double getMoneyAtMinute() {
		return moneyAtMinute;
	}

	/**
	 * Obtiene el número total de clics manuales realizados por el usuario desde el inicio de la partida.
	 * @return El sumatorio de clics registrados.
	 */
	public int getManualClicksTotal() {
		return manualClicksTotal;
	}

	/**
	 * Obtiene la cantidad total de recursos generados exclusivamente de forma pasiva por los generadores.
	 * @return El total de café producido automáticamente.
	 */
	public double getAutoGeneratedTotal() {
		return autoGeneratedTotal;
	}

	/**
	 * Obtiene la tasa de producción por segundo más alta alcanzada por el jugador hasta ese momento.
	 * @return El récord de producción pasiva registrado.
	 */
	public float getMaxProductionRate() {
		return maxProductionRate;
	}

	/**
	 * Obtiene la inversión total realizada por el jugador en la compra de generadores y mejoras.
	 * @return El gasto acumulado en el desarrollo de la infraestructura de producción.
	 */
	public double getUpgradesExpenses() {
		return upgradesExpenses;
	}
}